version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongo
    environment:
      AUTH: 'no'
      MONGODB_DATABASE: easygenerator
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6:
